[azure]
# Deployed VM will be added here with public IP
# simple_vm ansible_host=<public_ip> ansible_user=azureuser

[azure:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_user=azureuser
